
#
/system/framework/framework.jar
#
/system/framework/framework.jar
0
(/system/framework/framework-graphics.jar35
0
(/system/framework/framework-graphics.jar35
0
(/system/framework/framework-location.jar35
0
(/system/framework/framework-location.jar35

/system/framework/ext.jar

/system/framework/ext.jar
*
&/system/framework/telephony-common.jar
*
&/system/framework/telephony-common.jar
%
!/system/framework/voip-common.jar
%
!/system/framework/voip-common.jar
$
 /system/framework/ims-common.jar
$
 /system/framework/ims-common.jar
"
/system/framework/tcmiface.jar
"
/system/framework/tcmiface.jar
'
#/system/framework/telephony-ext.jar
'
#/system/framework/telephony-ext.jar
&
"/system/framework/qcom.fmradio.jar
&
"/system/framework/qcom.fmradio.jar
&
"/system/framework/QPerformance.jar
&
"/system/framework/QPerformance.jar
'
#/system/framework/UxPerformance.jar
'
#/system/framework/UxPerformance.jar
#
/system/framework/WfdCommon.jar
#
/system/framework/WfdCommon.jar
%
!/system/framework/miframework.jar
%
!/system/framework/miframework.jar
7
3/system/framework/ifaa_aidl_framework_src_files.jar
7
3/system/framework/ifaa_aidl_framework_src_files.jar
*
&/system/framework/subsys-framework.jar
*
&/system/framework/subsys-framework.jar
4
0/system/framework/vendor-telephony-framework.jar
4
0/system/framework/vendor-telephony-framework.jar
+
'/system/framework/ToolsManager-aidl.jar
+
'/system/framework/ToolsManager-aidl.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar